---
process_orders_task:
  description: Process the orders from the provided data, prioritizing procurement
    to ensure essential items are ordered on time for {company_name}.
  expected_output: A list of processed orders ready for submission to Odoo, with priority
    items highlighted.
  async_execution: false
  agent: order_processing_specialist
manage_transport_task:
  description: Manage transportation details, including updating pallet dimensions
    and tracking delivery timelines for {company_name}.
  expected_output: An updated report on transportation details, including pallet dimensions
    and estimated delivery timelines.
  async_execution: false
  agent: transport_management_expert
focus_on_project_task:
  description: Ensure the team focuses on one project at a time, coordinating efforts
    to maximize productivity for {company_name}.
  expected_output: A clear outline of the current project focus and allocated resources,
    ensuring no overlap with other projects.
  async_execution: false
  agent: project_focus_coordinator
generate_reports_task:
  description: Produce regular updates and reports on the status of orders and deliveries
    for stakeholders at {company_name}.
  expected_output: A comprehensive report detailing the status of orders and deliveries,
    including any issues or delays.
  async_execution: false
  agent: reporting_specialist
collect_client_data_task:
  description: Retrieve delivery information provided by clients via Jotform, ensuring
    accurate data collection for logistics management at {company_name}.
  expected_output: A compiled dataset of client delivery information, ready for analysis
    and use in logistics planning.
  async_execution: false
  agent: client_data_collector
